### ISSUE TITLE
cloned repo does nothing

### ISSUE THREAD

**Issue by estevanio** [learning-ionic/Chapter-8#7]
cloned the repository, ran npm install, ran bower update, installed the plugins, ran it and it just goes back to the main page after logging into google.

**Comment by arvindr21** [comment]
Can you see if there are any console errors?

**Comment by estevanio** [comment]
i dont get any when running it unless i have the -l flag, then it will show
application errors on the device.

**Comment by stavinopolis** [comment]
i don't see any.

**Comment by estevanio** [comment]
fixed by running "ionic plugin add cordova-plugin-whitelist"
